authorizations/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import Dashboard

from .views import AuthorizationCreateView
from .views import AuthorizationDetailView
from .views import AuthorizationUpdateView
from .views import AuthorizationPublishBylawView

urlpatterns = [

    url(r'^dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^add/(?P<manifestation_pk>\d+)$', AuthorizationCreateView.as_view(), name='authorization_add'),
    url(r'^(?P<pk>\d+)/$', AuthorizationDetailView.as_view(), name="authorization_detail"),
    url(r'^(?P<pk>\d+)/publish/$', AuthorizationPublishBylawView.as_view(), name='authorization_publish'),
    url(r'^(?P<pk>\d+)/edit/$', AuthorizationUpdateView.as_view(), name="authorization_update"),

]

ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sitemap\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^nouveautes/', include('nouveautes.urls', namespace='nouveautes')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
    url(r'^(?P<url>.*/)$', flatpages_views.flatpage),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
# coding: utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import ManifestationChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclarationNMChoose
from .views import PublicRoadMotorizedEventChoose
from .views import ManifestationPublicDetail

from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate

from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import DocumentComplementaireRequestView
from .views import DocumentComplementaireProvideView

from .views import MailToOrganisateursView
from .views import MailToTownHallsView

from sports.views import activites_par_discipline

urlpatterns = [

    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToOrganisateursView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^calendar/(?P<activite>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', ManifestationChoose.as_view(),
        name='manifestation_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^DeclarationNM/choose',
        DeclarationNMChoose.as_view(),
        name="declarationnm_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        ManifestationPublicDetail.as_view(),
        name="manifestation_detail"),

    # DeclarationNM urls
    url(r'^DeclarationNM/add/$',
        DeclarationNMCreate.as_view(),
        name="declarationnm_add"),
    url(r'^DeclarationNM/(?P<pk>\d+)/$',
        DeclarationNMDetail.as_view(),
        name="declarationnm_detail"),
    url(r'^DeclarationNM/(?P<pk>\d+)/edit/$',
        DeclarationNMUpdate.as_view(),
        name="declarationnm_update"),

    # AutorisationNM urls
    url(r'^AutorisationNM/add/$',
        AutorisationNMCreate.as_view(),
        name="autorisationnm_add"),
    url(r'^AutorisationNM/(?P<pk>\d+)/$',
        AutorisationNMDetail.as_view(),
        name="autorisationnm_detail"),
    url(r'^AutorisationNM/(?P<pk>\d+)/edit/$',
        AutorisationNMUpdate.as_view(),
        name="autorisationnm_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<manifestation_pk>\d+)/additional_data/add$',
        DocumentComplementaireRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        DocumentComplementaireProvideView.as_view(),
        name="additional_data_provide"),

    url(r'^activites_par_discipline/$',
        activites_par_discipline)
]

events/views.py
# coding: utf-8
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin

from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy

from django.db.models import Count
from django.db.models import Q

from django.http import HttpResponseRedirect

from django.shortcuts import get_object_or_404

from django.utils import timezone
from django.utils.decorators import method_decorator

from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from braces.views import LoginRequiredMixin, SuperuserRequiredMixin

from extra_views import CreateWithInlinesView, UpdateWithInlinesView

from administration.models import MairieAgent

from authorizations.decorators import instructeur_required

from contacts.forms import ContactInline

from sports.models import Activite

from .decorators import organisateur_required
from .decorators import owner_required

from .forms import DocumentComplementaireRequestForm
from .forms import DocumentComplementaireProvideForm
from .forms import UserUpdateForm
from .forms import AutorisationNMForm
from .forms import DeclarationNMForm
from .forms import MotorizedConcentrationForm
from .forms import MotorizedEventForm
from .forms import MotorizedRaceForm
from .forms import StructureForm

from .models import DocumentComplementaire
from .models import Manifestation
from .models import AutorisationNM
from .models import DeclarationNM
from .models import MotorizedConcentration
from .models import MotorizedEvent
from .models import MotorizedRace
from .models import Structure
from .models import Organisateur


class HomePage(TemplateView):
    template_name = 'events/home.html'


class Dashboard(ListView):
    model = Manifestation

    @method_decorator(organisateur_required)
    def dispatch(self, *args, **kwargs):
        return super(Dashboard, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        try:
            structure = self.request.user.organisateur.structure
        except Structure.DoesNotExist:
            structure = None
        return Manifestation.objects.filter(structure=structure).order_by('-pk')

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        return context


class ProfileDetailView(DetailView):
    model = User

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileDetailView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = '/accounts/profile'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user


class Calendar(ListView):
    model = Manifestation
    template_name = 'events/calendar.html'

    def get_queryset(self):
        now = timezone.now()
        return Manifestation.objects.filter(
            ~Q(autorisationnm__manifestationautorisation__id=None) |
            ~Q(declarationnm__manifestationdeclaration__id=None) |
            ~Q(motorizedevent__manifestationautorisation__id=None) |
            ~Q(motorizedrace__manifestationautorisation__id=None) |
            ~Q(motorizedconcentration__manifestationautorisation__id=None) |
            ~Q(motorizedconcentration__manifestationdeclaration__id=None),
            begin_date__gt=now,
        ).order_by('begin_date')

    def get_context_data(self, **kwargs):
        context = super(Calendar, self).get_context_data(**kwargs)
        context['activities'] = Activite.objects.annotate(num_manifestations=Count('manifestation'))\
            .filter(num_manifestations__gt=0).order_by('name')
        return context


class FilteredCalendar(Calendar):

    def get_queryset(self):
        return super(FilteredCalendar, self).get_queryset().filter(activite=self.kwargs['activite'])

    def get_context_data(self, **kwargs):
        context = super(FilteredCalendar, self).get_context_data(**kwargs)
        context['current_activite'] = int(self.kwargs['activite'])
        return context


class StructureCreate(CreateView):
    model = Structure
    form_class = StructureForm

    @method_decorator(organisateur_required)
    def dispatch(self, *args, **kwargs):
        return super(StructureCreate, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.organisateur = self.request.user.organisateur
        return super(StructureCreate, self).form_valid(form)


class StructureUpdateView(UpdateView):
    model = Structure
    form_class = StructureForm
    success_url = '/accounts/profile'

    @method_decorator(organisateur_required)
    def dispatch(self, *args, **kwargs):
        return super(StructureUpdateView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user.organisateur.structure


###########################################################
# Generic Choice View
###########################################################
class ChoiceView(TemplateView):

    @method_decorator(organisateur_required)
    def dispatch(self, *args, **kwargs):
        return super(ChoiceView, self).dispatch(*args, **kwargs)


###########################################################
# Types of Manifestation choices Views
###########################################################
class CreateRoute(ChoiceView):
    template_name = 'events/create_route.html'


class ManifestationChoose(ChoiceView):
    template_name = 'events/event_choose.html'


class NonMotorizedEventChoose(ChoiceView):
    template_name = 'events/nonmotorizedevent_choose.html'


class DeclarationNMChoose(ChoiceView):
    template_name = 'events/declarednonmotorizedevent_choose.html'


class MotorizedEventChoose(ChoiceView):
    template_name = 'events/motorizedevent_choose.html'


class PublicRoadMotorizedEventChoose(ChoiceView):
    template_name = 'events/publicroadmotorizedevent_choose.html'


###########################################################
# Manifestation Views (Generic)
###########################################################
class ManifestationDetail(DetailView):

    @method_decorator(owner_required)
    def dispatch(self, *args, **kwargs):
        return super(ManifestationDetail, self).dispatch(*args, **kwargs)


class ManifestationCreate(CreateWithInlinesView):
    inlines = [ContactInline]
    template_name = 'events/event_form.html'

    @method_decorator(organisateur_required)
    def dispatch(self, *args, **kwargs):
        return super(ManifestationCreate, self).dispatch(*args, **kwargs)

    def forms_valid(self, form, inlines):
        self.object.structure = self.request.user.organisateur.structure
        self.object = form.save()
        for formset in inlines:
            formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super(ManifestationCreate, self).get_form_kwargs()
        kwargs['routes'] = self.request.user.organisateur.get_openrunner_routes()
        return kwargs


class ManifestationUpdate(UpdateWithInlinesView):
    inlines = [ContactInline]
    template_name = 'events/event_form.html'

    @method_decorator(owner_required)
    def dispatch(self, *args, **kwargs):
        return super(ManifestationUpdate, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(ManifestationUpdate, self).get_form_kwargs()
        kwargs['routes'] = self.request.user.organisateur.get_openrunner_routes()
        # Here, we have to transform event routes from a string into a list
        # We use strip(',') to avoid errors caused by leading or trailing commas
        if kwargs['instance'].__dict__['openrunner_route']:
            kwargs['instance'].__dict__['openrunner_route'] = [int(route) for route in kwargs['instance'].__dict__['openrunner_route'].strip(',').split(',')]  # noqa
        return kwargs


###########################################################
# Manifestation Public View
###########################################################
class ManifestationPublicDetail(DetailView):
    model = Manifestation
    template_name = 'events/eventpublic_detail.html'


###########################################################
# DeclarationNM Views
###########################################################
class DeclarationNMDetail(ManifestationDetail):
    model = DeclarationNM


class DeclarationNMCreate(ManifestationCreate):
    model = DeclarationNM
    form_class = DeclarationNMForm


class DeclarationNMUpdate(ManifestationUpdate):
    model = DeclarationNM
    form_class = DeclarationNMForm


###########################################################
# AutorisationNM Views
###########################################################
class AutorisationNMDetail(ManifestationDetail):
    model = AutorisationNM


class AutorisationNMCreate(ManifestationCreate):
    model = AutorisationNM
    form_class = AutorisationNMForm


class AutorisationNMUpdate(ManifestationUpdate):
    model = AutorisationNM
    form_class = AutorisationNMForm


###########################################################
# MotorizedConcentration Views
###########################################################
class MotorizedConcentrationDetail(ManifestationDetail):
    model = MotorizedConcentration


class MotorizedConcentrationCreate(ManifestationCreate):
    model = MotorizedConcentration
    form_class = MotorizedConcentrationForm


class MotorizedConcentrationUpdate(ManifestationUpdate):
    model = MotorizedConcentration

events/templates/events/access_restricted.html
{% extends "events/base.html" %}

{% url from future %}
{% load i18n %}

{% block head_title %}Accès Restreint{% endblock %}
{% block page_title %}
    <h1>Accès Restreint</h1>
{% endblock %}

{% block content %}
    <p>Cette section du site est restreinte à certaines personnes seulement</p>
    <p><a href="{% url 'events:home_page' %}" class="btn btn-primary" role="button">Retour à la page d'accueil</a></p>
{% endblock %}

events/templates/events/base.html
{% load staticfiles %}

{% load i18n %}

<!DOCTYPE html>
<html>
    <head>
        <title>{{ DEPARTMENT_NAME }} {% block head_title %}{% endblock %}</title>
        {% block extra_head %}
        {% endblock %}
        <meta charset='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <!-- Bootstrap -->
        <link href='{% static 'events/css/bootstrap.min.css' %}' rel='stylesheet' type='text/css'>
        <link href='{% static 'events/css/font-awesome.min.css' %}' rel='stylesheet' type='text/css'>
        <link href='{% static 'events/css/default.css' %}' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
        <link href='//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.css' rel='stylesheet' type='text/css'>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'></script>
        <script src='https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js'></script>
        <![endif]-->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src='//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
        <script src='{% static 'events/js/bootstrap.min.js' %}'></script>
    </head>
    <body style="background-color: {{ DEPARTMENT_BKG_COLOR }};">
        <nav class='navbar navbar-inverse navbar-fixed-top' role='navigation'>
            <div class='container'>
                <div class='navbar-header'>
                    <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
                        <span class='sr-only'>Toggle navigation</span>
                        <span class='icon-bar'></span>
                        <span class='icon-bar'></span>
                        <span class='icon-bar'></span>
                    </button>
                    <a class='navbar-brand' href='{% url 'events:home_page' %}'>
                        <img alt='Manifestations sportives en loire et développement durable' src='{% static 'events/img/manifloire_brand.png' %}'>
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class='collapse navbar-collapse'>
                    <ul class='nav navbar-nav navbar-right'>
                        {% if user.is_authenticated %}
                            {% if user.organisateur %}
                                <li><a href='{% url 'profile' %}'><i class="fa fa-user"></i> {{ user.username }} (Organisateur - {{ DEPARTMENT_NAME }})</a></li>
                                <li><a href='{% url 'events:dashboard' %}'><i class="fa fa-tachometer"></i> Tableau de bord</a></li>
                            {% elif user.instructeur %}
                                <li><a href='{% url 'profile' %}'><i class="fa fa-user"></i> {{ user.username }} (Instructeur - {{ DEPARTMENT_NAME }})</a></li>
                                <li><a href='{% url 'authorizations:dashboard' %}'><i class="fa fa-tachometer"></i> Tableau de bord</a></li>
                            {% elif user.agent %}
                                {% if user.agent.edsragent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.edsragent.edsr }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.brigadeagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.brigadeagent.brigade }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.ggdagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.ggdagent.ggd }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.sdisagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.sdisagent.sdis }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.codisagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.codisagent.codis }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.cisagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.cisagent.cis }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.ddspagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.ddspagent.ddsp }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.federationagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.federationagent.federation }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.serviceagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.serviceagent.service }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.townhallagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.mairieagent.commune }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.cgagent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.cgagent.cg }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agent.cgsuperieuragent %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agent.cgsuperieuragent.cg }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% endif %}
                                <li><a href='{% url 'agreements:dashboard' %}'><i class="fa fa-tachometer"></i> Tableau de bord</a></li>
                            {% elif user.agentlocal %}
                                {% if user.agentlocal.compagnieagentlocal %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agentlocal.compagnieagentlocal.compagnie }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agentlocal.cgdagentlocal %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agentlocal.cgdagentlocal.cgd }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agentlocal.edsragentlocal %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agentlocal.edsragentlocal.edsr }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agentlocal.commissariatagentlocal %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agentlocal.commissariatagentlocal.commissariat }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% elif user.agentlocal.cgserviceagentlocal %}
                                    <li><a href=''><i class="fa fa-user"></i> {{ user.username }} ({{ user.agentlocal.cgserviceagentlocal.cg_service }} - {{ DEPARTMENT_NAME }})</a></li>
                                {% endif %}
                                <li><a href='{% url 'sub_agreements:dashboard' %}'><i class="fa fa-tachometer"></i> Tableau de bord</a></li>
                            {% endif %}
                            {% if user.is_superuser %}
                                <li><a href='{% url 'admin:index' %}'><i class="fa fa-cog"></i> Administration système</a></li>
                            {% endif %}
                            <li class="active">
                                <a href='{% url 'account_logout' %}'><i class="fa fa-sign-out"></i> Déconnexion</a>
                            </li>
                        {% else %}
                            <li class="active">
                                <a href='{% url 'account_login' %}'><i class="fa fa-sign-in"></i> Connexion</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block body %}
            <div class='container'>
                {% if messages %}
                    <br />
                    <div class='container'>
                        {% for message in messages %}
                            <div class='alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissable'>
                                <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
                                <strong>{{message}}</strong>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {% include "nouveautes/nouveaute_available.html" %}

                <div class='page-header'>
                    {% block page_title %}{% endblock %}
                </div>

                {% block content %}
                {% endblock %}
            </div>
        {% endblock %}

        {% block extra_body %}
        {% endblock %}

        <footer role='contentinfo'>
            <div class="container">
                <h2 class='text-center'>
                    Une interface web simplifiant considérablement les démarches entre les
                    organisateurs d'événements sportifs, l'état et l'ensemble des services
                    consultés pour avis.
                </h2>
                <div id="footer-info" class='text-center'><a href="http://www.openscop.fr">Openscop</a> - {{ DATE }} - <span  data-toggle="tooltip" data-placement="bottom" title="{{ COMMIT }}">Version {{ VERSION }}</span> - <a href="/mentions-legales/">Mentions légales</a> - <a href="/CGU/manifestationsportiveloire/">Conditions Générales d'Utilisation</a></div>
            </div>
        </footer>
        <script src='//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js'></script>
        <script>
            function dateSorter(date1, date2) {
                var date12 = date1.split('/').reverse().join('');
                var date22 = date2.split('/').reverse().join('');
                if (date12 > date22) return 1;
                if (date12 < date22) return -1;
                return 0;
            };
        </script>
        {% block extra_js %}
        {% endblock %}
        <script src='{% static 'events/js/common.js' %}'></script>
    </body>
</html>

events/templates/events/event_panel_instructor.html
{% extends "events/event_panel.html" %}

{% load i18n %}

{% block event_description %}
<div id="event" class="panel panel-default tab-pane fade">
    {% include 'events/event_description.html' %}
</div>
{% endblock %}