authorizations/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import Dashboard

from .views import AuthorizationCreateView
from .views import AuthorizationDetailView
from .views import AuthorizationUpdateView
from .views import AuthorizationPublishBylawView

urlpatterns = [

    url(r'^dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^add/(?P<manifestation_pk>\d+)$', AuthorizationCreateView.as_view(), name='authorization_add'),
    url(r'^(?P<pk>\d+)/$', AuthorizationDetailView.as_view(), name="authorization_detail"),
    url(r'^(?P<pk>\d+)/publish/$', AuthorizationPublishBylawView.as_view(), name='authorization_publish'),
    url(r'^(?P<pk>\d+)/edit/$', AuthorizationUpdateView.as_view(), name="authorization_update"),

]

ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sitemap\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^nouveautes/', include('nouveautes.urls', namespace='nouveautes')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
    url(r'^(?P<url>.*/)$', flatpages_views.flatpage),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

declarations/urls.py
# coding: utf-8
from django.conf.urls import url

from .views import DeclarationCreateView
from .views import DeclarationDetailView
from .views import DeclarationPublishReceiptView


urlpatterns = [
    url(r'^(?P<pk>\d+)/publish/$', DeclarationPublishReceiptView.as_view(), name='declaration_publish'),
    url(r'^add/(?P<manifestation_pk>\d+)$', DeclarationCreateView.as_view(), name='declaration_add'),
    url(r'^(?P<pk>\d+)/$', DeclarationDetailView.as_view(), name='declaration_detail')
]

events/urls.py
# coding: utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import ManifestationChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclarationNMChoose
from .views import PublicRoadMotorizedEventChoose
from .views import ManifestationPublicDetail

from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate

from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import DocumentComplementaireRequestView
from .views import DocumentComplementaireProvideView

from .views import MailToOrganisateursView
from .views import MailToTownHallsView

from sports.views import activites_par_discipline

urlpatterns = [

    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToOrganisateursView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^calendar/(?P<activite>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', ManifestationChoose.as_view(),
        name='manifestation_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^DeclarationNM/choose',
        DeclarationNMChoose.as_view(),
        name="declarationnm_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        ManifestationPublicDetail.as_view(),
        name="manifestation_detail"),

    # DeclarationNM urls
    url(r'^DeclarationNM/add/$',
        DeclarationNMCreate.as_view(),
        name="declarationnm_add"),
    url(r'^DeclarationNM/(?P<pk>\d+)/$',
        DeclarationNMDetail.as_view(),
        name="declarationnm_detail"),
    url(r'^DeclarationNM/(?P<pk>\d+)/edit/$',
        DeclarationNMUpdate.as_view(),
        name="declarationnm_update"),

    # AutorisationNM urls
    url(r'^AutorisationNM/add/$',
        AutorisationNMCreate.as_view(),
        name="autorisationnm_add"),
    url(r'^AutorisationNM/(?P<pk>\d+)/$',
        AutorisationNMDetail.as_view(),
        name="autorisationnm_detail"),
    url(r'^AutorisationNM/(?P<pk>\d+)/edit/$',
        AutorisationNMUpdate.as_view(),
        name="autorisationnm_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<manifestation_pk>\d+)/additional_data/add$',
        DocumentComplementaireRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        DocumentComplementaireProvideView.as_view(),
        name="additional_data_provide"),

    url(r'^activites_par_discipline/$',
        activites_par_discipline)
]

authorizations/forms.py
# coding: utf-8
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from ddcs_loire.utils import GenericForm

from crispy_forms.layout import Submit, Layout, Fieldset
from crispy_forms.bootstrap import FormActions

from .models import ManifestationAutorisation


class AuthorizationForm(GenericForm):

    class Meta:
        model = ManifestationAutorisation
        exclude = ['manifestation', 'creation_date', 'dispatch_date', 'state', 'concerned_cities', 'concerned_services', 'ddsp_concerned', 'edsr_concerned', 'ggd_concerned', 'sdis_concerned', 'cg_concerned', 'bylaw',]

    def __init__(self, *args, **kwargs):
        super(AuthorizationForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                FormActions(
                        Submit('save', "demander une autorisation".capitalize())
                )
        )


class AuthorizationDispatchForm(GenericForm):

    class Meta:
        model = ManifestationAutorisation
        exclude = ['manifestation', 'creation_date', 'dispatch_date', 'state', 'bylaw',]

    def __init__(self, *args, **kwargs):
        super(AuthorizationDispatchForm, self).__init__(*args, **kwargs)
        if settings.DEPARTMENT_SETTINGS['EDSR_OR_GGD'].startswith('GGD'):
            self.fields['ggd_concerned'].initial = True
            self.fields['edsr_concerned'].initial = False
            self.fields['edsr_concerned'].widget = forms.HiddenInput()
        elif settings.DEPARTMENT_SETTINGS['EDSR_OR_GGD'] == 'EDSR':
            self.fields['edsr_concerned'].initial = True
            self.fields['ggd_concerned'].initial = False
            self.fields['ggd_concerned'].widget = forms.HiddenInput()
        self.helper.layout = Layout(
            Fieldset("avis requis".capitalize(), 'ddsp_concerned', 'edsr_concerned', 'ggd_concerned', 'sdis_concerned', 'cg_concerned', 'concerned_cities', 'concerned_services',),
            FormActions(
                Submit('save', "distribuer".capitalize())
            )
        )


class AuthorizationPublishBylawForm(GenericForm):

    class Meta:
        model = ManifestationAutorisation
        fields = ['bylaw']

    def __init__(self, *args, **kwargs):
        super(AuthorizationPublishBylawForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            Fieldset(
                "choisissez le fichier de l'arrêté".capitalize(),
                'bylaw',
            ),
            FormActions(
                Submit('save', "publier l'arrêté".capitalize())
            )
        )

    def clean_bylaw(self):
        """ Vérifier le champ de fichier d'arrêté """
        data = self.cleaned_data['bylaw']
        if not data:
            raise forms.ValidationError("Vous devez spécifier un fichier contenant l'arrêté")
        return data

authorizations/views.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from declarations.models import ManifestationDeclaration

from events.decorators import organisateur_required
from events.models import Manifestation

from .decorators import instructeur_required

from .forms import AuthorizationPublishBylawForm
from .forms import AuthorizationForm
from .forms import AuthorizationDispatchForm

from .models import ManifestationAutorisation


class Dashboard(ListView):
    model = ManifestationAutorisation

    @method_decorator(instructeur_required)
    def dispatch(self, *args, **kwargs):
        return super(Dashboard, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        instructeur = self.request.user.instructeur
        return ManifestationAutorisation.objects.to_process().for_instructor(instructeur).closest_first()

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        instructeur = self.request.user.instructeur
        context['declarations'] = ManifestationDeclaration.objects.to_process().for_instructor(instructeur).closest_first()
        return context


class AuthorizationCreateView(CreateView):
    model = ManifestationAutorisation
    form_class = AuthorizationForm

    @method_decorator(organisateur_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.manifestation = get_object_or_404(Manifestation, pk=self.kwargs['manifestation_pk'])
        return super(AuthorizationCreateView, self).form_valid(form)

    def get_success_url(self):
        try:
            self.object.manifestation.autorisationnm
        except:
            try:
                self.object.manifestation.motorizedconcentration
            except:
                try:
                    self.object.manifestation.motorizedmanifestation
                except:
                    try:
                        self.object.manifestation.motorizedrace
                    except:
                        return reverse('events:home_page')
                    else:
                        return reverse('events:motorizedrace_detail', kwargs={'pk': self.object.manifestation.pk})
                else:
                    return reverse('events:motorizedevent_detail', kwargs={'pk': self.object.manifestation.pk})
            else:
                return reverse('events:motorizedconcentration_detail', kwargs={'pk': self.object.manifestation.pk})
        else:
            return reverse('events:autorisationnm_detail', kwargs={'pk': self.object.manifestation.pk})


class AuthorizationDetailView(DetailView):
    model = ManifestationAutorisation

    @method_decorator(instructeur_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationDetailView, self).dispatch(*args, **kwargs)


class AuthorizationUpdateView(UpdateView):
    model = ManifestationAutorisation
    form_class = AuthorizationDispatchForm
    success_url = "/authorizations/%(id)s"

    @method_decorator(instructeur_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.dispatch()
        return super(AuthorizationUpdateView, self).form_valid(form)


class AuthorizationPublishBylawView(UpdateView):
    model = ManifestationAutorisation
    form_class = AuthorizationPublishBylawForm
    template_name_suffix = '_publish_form'

    @method_decorator(instructeur_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthorizationPublishBylawView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.publish()
        return super(AuthorizationPublishBylawView, self).form_valid(form)

authorizations/templates/authorizations/manifestationautorisation_detail.html
{% extends "events/base.html" %}

{# load url from future #}
{% load i18n %}

{% block head_title %}
    Autorisation de manifestation
{% endblock %}

{% block page_title %}
    <h1>{{ object.manifestation|capfirst }}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            <ul class="nav nav-pills">
                <li class="active"><a href="#authorization" data-toggle="pill"><i class="fa fa-diamond" aria-hidden="true"></i> Autorisation</a></li>
                <li><a href="#event" data-toggle="pill"><i class="fa fa-flag-checkered" aria-hidden="true"></i> Détail de la manifestation</a></li>
                {% include 'events/event_tabs.html' with object=object.manifestation %}
            </ul>
            <div class="tab-content">
                <div id="authorization" class="panel panel-default tab-pane fade in active">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-flag-checkered" aria-hidden="true"></i>{{ object.manifestation|capfirst }}
                        </h3>
                    </div>
                    <ul class="list-group">
                        {% if object.manifestation.creation_date %}
                            <li class="list-group-item">Date de création de la manifestation : {{ object.manifestation.creation_date }}</li>
                      	{% endif %}
                        <li class="list-group-item">Date de demande d'autorisation : {{ object.creation_date }}</li>
                        <li class="list-group-item">Type de manifestation : {{ object }}</li>
                        {% if object.bylaw %}
                            <li class="list-group-item">Arrêté : <a href="{{ object.bylaw.url }}" target='_blank'>{{ object.bylaw }}</a></li>
                        {% endif %}
                    </ul>
                    {% for avis in object.aviss.all %}
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-bookmark" aria-hidden="true"></i>Avis :
                                {% if avis.serviceavis %}
                                    {{ avis.serviceavis.service }}
                                {% elif avis.federationavis %}
                                    {{ avis.federationavis.get_federation }}
                                {% elif avis.mairieavis %}
                                    {{ avis.mairieavis.commune }}
                                {% elif avis.edsravis %}
                                    {{ avis.edsravis.get_edsr }}
                                {% elif avis.sdisavis %}
                                    {{ avis.sdisavis.get_sdis }}
                                {% elif avis.ddspavis %}
                                    {{ avis.ddspavis.get_ddsp }}
                                {% elif avis.cgavis %}
                                    {{ avis.cgavis.get_cg }}
                                {% elif avis.ggdavis %}
                                    {{ avis.ggdavis.get_ggd }}
                                {% endif %}
                                {% if avis.state != 'acknowledged' and object.state != 'published' %}
                                    {% if avis.serviceavis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:service_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% elif avis.federationavis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:federal_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% elif avis.mairieavis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:townhall_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% elif avis.edsravis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:edsr_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% elif avis.sdisavis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:sdis_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% elif avis.ddspavis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:ddsp_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% elif avis.cgavis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:cg_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% elif avis.ggdavis %}
                                        <a class="btn btn-primary pull-right" href="{% url 'agreements:ggd_agreement_resend' pk=avis.pk %}" role="button"><i class="fa fa-paper-plane" aria-hidden="true"></i>Envoyer à nouveau la demande d'avis</a>
                                    {% endif %}
                                {% endif %}
                            </h3>
                        </div>
                        <ul class="list-group">
                            <li class="list-group-item">L'avis a été envoyé le {{ avis.request_date }}</li>
                            {% ifnotequal avis.state 'acknowledged' %}
                                <li class="list-group-item">L'avis est en cours d'examen</li>
                            {% else %}
                                <li class="list-group-item">Date de l'avis : {{ avis.reply_date }}</li>
                                <li class="list-group-item">Favorable : {{ avis.favorable|yesno|title }}</li>
                                <li class="list-group-item">Prescriptions : {{ avis.prescriptions|linebreaks }}</li>
                                {% if avis.attached_document %}
                                    <li class="list-group-item">Document joint :
                                        <a href="{{ avis.attached_document.url }}" target='_blank'>{{ avis.attached_document }}</a>
                                    </li>
                                {% endif %}
                            {% endifnotequal %}
                        </ul>
                    {% endfor %}
                </div>
                {% include 'events/event_panel_instructor.html' with object=object.manifestation %}
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-magic" aria-hidden="true"></i> Actions disponibles</h3>
                </div>
                <div class="panel-body">
                    <p>Retrouvez ici toutes les actions disponibles liées à cette manifestation</p>
                </div>
                <ul class="list-group">
                    {% if object.state != 'published' %}
                        <li class="list-group-item">
                            <a href="{% url 'events:additional_data_add' manifestation_pk=object.manifestation.id %}" class="btn" role="button">
                                <i class="fa fa-plus-square" aria-hidden="true"></i> Demander plus d'informations
                            </a>
                        </li>
                    {% endif %}
                    {% if object.state == 'created' %}
                        <li class="list-group-item">
                            <a href="{% url 'authorizations:authorization_update' pk=object.id %}" class="btn" role="button">
                                Distribuer les demandes d'avis
                            </a>
                        </li>
                    {% elif object.state == 'dispatched' %}
                        <li class="list-group-item">
                            <a href="{% url 'authorizations:authorization_update' pk=object.id %}" class="btn" role="button">
                                <i class="fa fa-bookmark" aria-hidden="true"></i> Ajouter des demandes d'avis
                            </a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'authorizations:authorization_publish' pk=object.id %}" class="btn" role="button">
                                <i class="fa fa-key" aria-hidden="true"></i> Publier l'arrêté
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <a href="{% url 'authorizations:dashboard' %}" class="btn" role="button">
                Revenir au <i class="fa fa-tachometer" aria-hidden="true"></i>tableau de bord
            </a>
        </div>
    </div>
{% endblock %}

authorizations/templates/authorizations/manifestationautorisation_form.html
{% extends "events/base_form.html" %}

{% load i18n %}
{% load staticfiles %}

{% block head_title %}
    Autorisation de manifestation sportive
{% endblock %}

{% block page_title %}
    <h1>Autorisation de manifestation sportive</h1>
{% endblock %}

{% block extra_js %}
    <script src='{% static 'events/js/bootstrap-multiselect.js' %}'></script>
    <link href='{% static 'events/css/bootstrap-multiselect.css' %}' rel='stylesheet' type='text/css'>
    <script src='{% static 'authorizations/js/bootstrap-multiselect-authorizations.js' %}'></script>
{% endblock %}

authorizations/templates/authorizations/manifestationautorisation_list.html
{% extends "events/base.html" %}

{# load url from future #}
{% load i18n %}

{% block head_title %}
    Tableau de bord instructeur
{% endblock %}

{% block page_title %}
    <h1><i class="fa fa-tachometer"></i> Tableau de bord</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3><i class="fa fa-diamond" aria-hidden="true"></i> Autorisations<br></h3>

            <div class="panel panel-default authorizations-requested">
                <div class="list-group">
                    {% for authorization in object_list %}
                        <a class="list-group-item
                            {% if authorization.state == 'published' %}
                                list-group-item-success
                            {% elif authorization.state == 'dispatched' %}
                                list-group-item-warning
                            {% elif authorization.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'authorizations:authorization_detail' authorization.id %}">{{ authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ authorization.manifestation }}
                            {% if not authorization.state == 'created' %}
                                {% if authorization.all_agreements_validated %}
                                    <span class="label label-success top-right"><i class="fa fa-check"></i></span>
                                {% else %}
                                    <span class="label label-default top-right">{{ authorization.agreements_missing }} Avis manquants</span>
                                {% endif %}
                            {% endif %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucune autorisation à gérer</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <h3><i class="fa fa-bullseye" aria-hidden="true"></i> Déclarations</h3>

            <div class="panel panel-default declarations">
                <div class="list-group">
                    {% for declaration in declarations %}
                        <a class="list-group-item
                            {% if declaration.state == 'published' %}
                                list-group-item-success
                            {% elif declaration.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'declarations:declaration_detail' declaration.id %}">{{ declaration.manifestation.begin_date|date:"d/m/Y" }}
                            : {{ declaration.manifestation }}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucune déclaration à gérer</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
        {% include "notifications/actions_list.html" %}
    </div>
    <div class="col-sm-6">
        {% include "notifications/notifications_list.html" %}
    </div>
    </div>
{% endblock %}

authorizations/templates/authorizations/manifestationautorisation_publish_form.html
{% extends "events/base_form.html" %}

{% load i18n %}

{% block head_title %}publication de l'arrêté d'autorisation{% endblock %}
{% block page_title %}
    <h1>publication de l'arrêté d'autorisation</h1>
{% endblock %}