ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sitemap\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^nouveautes/', include('nouveautes.urls', namespace='nouveautes')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
    url(r'^(?P<url>.*/)$', flatpages_views.flatpage),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
# coding: utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import ManifestationChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclarationNMChoose
from .views import PublicRoadMotorizedEventChoose
from .views import ManifestationPublicDetail

from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate

from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import DocumentComplementaireRequestView
from .views import DocumentComplementaireProvideView

from .views import MailToOrganisateursView
from .views import MailToTownHallsView

from sports.views import activites_par_discipline

urlpatterns = [

    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToOrganisateursView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^calendar/(?P<activite>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', ManifestationChoose.as_view(),
        name='manifestation_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^DeclarationNM/choose',
        DeclarationNMChoose.as_view(),
        name="declarationnm_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        ManifestationPublicDetail.as_view(),
        name="manifestation_detail"),

    # DeclarationNM urls
    url(r'^DeclarationNM/add/$',
        DeclarationNMCreate.as_view(),
        name="declarationnm_add"),
    url(r'^DeclarationNM/(?P<pk>\d+)/$',
        DeclarationNMDetail.as_view(),
        name="declarationnm_detail"),
    url(r'^DeclarationNM/(?P<pk>\d+)/edit/$',
        DeclarationNMUpdate.as_view(),
        name="declarationnm_update"),

    # AutorisationNM urls
    url(r'^AutorisationNM/add/$',
        AutorisationNMCreate.as_view(),
        name="autorisationnm_add"),
    url(r'^AutorisationNM/(?P<pk>\d+)/$',
        AutorisationNMDetail.as_view(),
        name="autorisationnm_detail"),
    url(r'^AutorisationNM/(?P<pk>\d+)/edit/$',
        AutorisationNMUpdate.as_view(),
        name="autorisationnm_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<manifestation_pk>\d+)/additional_data/add$',
        DocumentComplementaireRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        DocumentComplementaireProvideView.as_view(),
        name="additional_data_provide"),

    url(r'^activites_par_discipline/$',
        activites_par_discipline)
]

sub_agreements/urls.py
# coding: utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from sub_agreements.views import PreAvisEDSRDetail, PreAvisEDSRAcknowledge
from .views import Dashboard

from .views import PreAvisCGDAcknowledge
from .views import PreAvisCGDDetail
from .views import NotifyBrigadesView

from .views import PreAvisCompagnieAcknowledge
from .views import PreAvisCompagnieDetail
from .views import NotifyCISView

from .views import PreAvisCommissariatAcknowledge
from .views import PreAvisCommissariatDetail

from .views import PreAvisServiceCGAcknowledge
from .views import PreAvisServiceCGDetail

urlpatterns = [

    url(r'^dashboard/$', Dashboard.as_view(),
        name='dashboard'),
    # CGD SubAgreements
    url(r'^cgd/(?P<pk>\d+)/$',
        PreAvisCGDDetail.as_view(),
        name='cgd_subagreement_detail'),
    url(r'^cgd/(?P<pk>\d+)/acknowledge/$',
        PreAvisCGDAcknowledge.as_view(),
        name='cgd_subagreement_acknowledge'),
    url(r'^cgd/(?P<pk>\d+)/notify_brigades/$',
        NotifyBrigadesView.as_view(),
        name='notify_brigades'),
    # EDSR SubAgreements
    url(r'^edsr/(?P<pk>\d+)/$',
        PreAvisEDSRDetail.as_view(),
        name='edsr_subagreement_detail'),
    url(r'^edsr/(?P<pk>\d+)/acknowledge/$',
        PreAvisEDSRAcknowledge.as_view(),
        name='edsr_subagreement_acknowledge'),
    # Company SubAgreements
    url(r'^company/(?P<pk>\d+)/$',
        PreAvisCompagnieDetail.as_view(),
        name='company_subagreement_detail'),
    url(r'^company/(?P<pk>\d+)/acknowledge/$',
        PreAvisCompagnieAcknowledge.as_view(),
        name='company_subagreement_acknowledge'),
    url(r'^company/(?P<pk>\d+)/notify_cis/$',
        NotifyCISView.as_view(),
        name='notify_cis'),
    # Commissariat SubAgreements
    url(r'^commissariat/(?P<pk>\d+)/$',
        PreAvisCommissariatDetail.as_view(),
        name='commissariat_subagreement_detail'),
    url(r'^commissariat/(?P<pk>\d+)/acknowledge/$',
        PreAvisCommissariatAcknowledge.as_view(),
        name='commissariat_subagreement_acknowledge'),
    # CG Service SubAgreements
    url(r'^cgservice/(?P<pk>\d+)/$',
        PreAvisServiceCGDetail.as_view(),
        name='cgservice_subagreement_detail'),
    url(r'^cgservice/(?P<pk>\d+)/acknowledge/$',
        PreAvisServiceCGAcknowledge.as_view(),
        name='cgservice_subagreement_acknowledge'),
]

sub_agreements/views.py
# coding: utf-8
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView
from django.views.generic.edit import UpdateView

from agreements.views import BaseAcknowledgeView
from sub_agreements.decorators import edsr_agent_required
from sub_agreements.models import PreAvisEDSR
from .decorators import cgd_agent_required
from .decorators import cgservice_agent_required
from .decorators import commissariat_agent_required
from .decorators import company_agent_required
from .decorators import sub_agent_required
from .forms import NotifyBrigadesForm
from .forms import NotifyCISForm
from .forms import PreAvisForm
from .models import PreAvisCGD
from .models import PreAvisServiceCG
from .models import PreAvisCommissariat
from .models import PreAvisCompagnie
from .models import PreAvis


class Dashboard(ListView):
    model = PreAvis

    @method_decorator(sub_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(Dashboard, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        agentlocal = self.request.user.agentlocal
        # agent = self.request.user.agent
        # Liste de ce que doit voir un agent dans son dashboard
        results = {
            'compagnieagentlocal': PreAvisCompagnie.objects.to_process().filter(
                company=agentlocal.compagnieagentlocal.compagnie
            ) if hasattr(agentlocal, 'compagnieagentlocal') else None
            ,
            'cgdagentlocal': PreAvisCGD.objects.to_process().filter(
                gendarmerie_company=agentlocal.cgdagentlocal.cgd
            ) if hasattr(agentlocal, 'cgdagentlocal') else None
            ,
            'commissariatagentlocal': PreAvisCommissariat.objects.to_process().filter(
                commissariat=agentlocal.commissariatagentlocal.commissariat
            ) if hasattr(agentlocal, 'commissariatagentlocal') else None
            ,
            'cgserviceagentlocal': PreAvisServiceCG.objects.to_process().filter(
                cg_service=agentlocal.cgserviceagentlocal.cg_service
            ) if hasattr(agentlocal, 'cgserviceagentlocal') else None
            ,
            'edsragentlocal': PreAvisEDSR.objects.to_process().filter(
                edsr=agentlocal.edsragentlocal.edsr) if hasattr(
                agentlocal, 'edsragentlocal') else None
            ,
        }
        # Parcourir les clés disponibles, en tant qu'attributs de agent
        # Si un attribut ne provoque pas d'erreur, renvoyer le queryset approprié
        # Rappel: Les querysets ne sont pas évalués même lorsqu'ils sont retournés,
        # ils ne sont évalués que lorsqu'ils sont parcourus
        for agentname in results:
            try:
                getattr(agentlocal, agentname)
                return results[agentname]
            except (ObjectDoesNotExist, AttributeError):
                pass
        raise PreAvis.DoesNotExist("L'utilisateur courant doit être un agent local.")

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        return context


###########################################################
# CGDSub Agreements Views
###########################################################
class PreAvisCGDDetail(DetailView):
    model = PreAvisCGD

    @method_decorator(cgd_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisCGDDetail, self).dispatch(*args, **kwargs)


class PreAvisCGDAcknowledge(BaseAcknowledgeView):
    model = PreAvisCGD
    form_class = PreAvisForm

    @method_decorator(cgd_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisCGDAcknowledge,
                     self).dispatch(*args, **kwargs)


class NotifyBrigadesView(UpdateView):
    model = PreAvisCGD
    form_class = NotifyBrigadesForm
    template_name_suffix = '_notify_form'

    @method_decorator(cgd_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(NotifyBrigadesView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        response = super(NotifyBrigadesView, self).form_valid(form)
        form.instance.notify_brigades()
        form.instance.save()
        return response


###########################################################
# EDSR Sub Agreements Views
###########################################################
class PreAvisEDSRDetail(DetailView):
    model = PreAvisEDSR

    @method_decorator(edsr_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisEDSRDetail, self).dispatch(*args, **kwargs)


class PreAvisEDSRAcknowledge(BaseAcknowledgeView):
    model = PreAvisEDSR
    form_class = PreAvisForm

    @method_decorator(edsr_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisEDSRAcknowledge, self).dispatch(*args, **kwargs)


###########################################################
# CompanySub Agreements Views
###########################################################
class PreAvisCompagnieDetail(DetailView):
    model = PreAvisCompagnie

    @method_decorator(company_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisCompagnieDetail, self).dispatch(*args, **kwargs)


class PreAvisCompagnieAcknowledge(BaseAcknowledgeView):  # noqa pylint: disable=R0901
    model = PreAvisCompagnie
    form_class = PreAvisForm

    @method_decorator(company_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisCompagnieAcknowledge,
                     self).dispatch(*args, **kwargs)


class NotifyCISView(UpdateView):
    model = PreAvisCompagnie
    form_class = NotifyCISForm
    template_name_suffix = '_notify_form'

    @method_decorator(company_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(NotifyCISView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        response = super(NotifyCISView, self).form_valid(form)
        form.instance.notify_cis()
        form.instance.save()
        return response


###########################################################
# CommissariatSub Agreements Views
###########################################################
class PreAvisCommissariatDetail(DetailView):
    model = PreAvisCommissariat

    @method_decorator(commissariat_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisCommissariatDetail,
                     self).dispatch(*args, **kwargs)


class PreAvisCommissariatAcknowledge(BaseAcknowledgeView):  # noqa pylint: disable=R0901
    model = PreAvisCommissariat
    form_class = PreAvisForm

    @method_decorator(commissariat_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisCommissariatAcknowledge,
                     self).dispatch(*args, **kwargs)


###########################################################
# CGServiceSub Agreements Views
###########################################################
class PreAvisServiceCGDetail(DetailView):
    model = PreAvisServiceCG

    @method_decorator(cgservice_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisServiceCGDetail,
                     self).dispatch(*args, **kwargs)


class PreAvisServiceCGAcknowledge(BaseAcknowledgeView):  # noqa pylint: disable=R0901
    model = PreAvisServiceCG
    form_class = PreAvisForm

    @method_decorator(cgservice_agent_required)
    def dispatch(self, *args, **kwargs):
        return super(PreAvisServiceCGAcknowledge,
                     self).dispatch(*args, **kwargs)

sub_agreements/templates/sub_agreements/preavis_form.html
{% extends "events/base_form.html" %}

{% load i18n %}

{% block head_title %}Rendre le pré-avis{% endblock %}
{% block page_title %}
    <h1>Rendre le pré-avis</h1>
{% endblock %}

sub_agreements/templates/sub_agreements/preavis_list.html
{% extends "events/base.html" %}


{% load i18n %}

{% block head_title %}
    Tableau de Bord
{% endblock %}

{% block page_title %}
    <h1><i class="fa fa-tachometer" aria-hidden="true"></i> Tableau de Bord</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3><i class="fa fa-tags" aria-hidden="true"></i> Pré-avis demandés</h3>
            <div class="panel panel-default">
                <div class="list-group">
                    {% for sub_agreement in object_list %}
                        <a class="list-group-item
                            {% if sub_agreement.state == 'acknowledged' %}
                                list-group-item-success
                            {% elif sub_agreement.state == 'notified' %}
                                list-group-item-warning
                            {% elif sub_agreement.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                            {% block subagreement_item %}{% endblock %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucune demande de pré-avis à traiter</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                {% include "notifications/actions_list.html" %}
            <div class="row">
            </div>
                {% include "notifications/notifications_list.html" %}
            </div>
        </div>
    </div>
{% endblock %}

sub_agreements/templates/sub_agreements/preaviscgd_detail.html
{% extends "sub_agreements/preavis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' or object.state == 'notified' %}
        <a href="{% url 'sub_agreements:notify_brigades' pk=object.id %}" class="btn" role="button">
            Informer les brigades concernées
        </a>
    {% endif %}
    {% if object.state == 'notified' %}
        <a href="{% url 'sub_agreements:cgd_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            Rendre le pré-avis
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/preaviscgd_list.html
{% extends "sub_agreements/preavis_list.html" %}

{% block subagreement_item %}
    href="{% url 'sub_agreements:cgd_subagreement_detail' sub_agreement.id %}">
        {{ sub_agreement }}
{% endblock %}

sub_agreements/templates/sub_agreements/preaviscommissariat_ack_form.html
{% extends "sub_agreements/preavis_form.html" %}

sub_agreements/templates/sub_agreements/preaviscommissariat_detail.html
{% extends "sub_agreements/preavis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'sub_agreements:commissariat_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            Rendre le pré-avis
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/preaviscommissariat_list.html
{% extends "sub_agreements/preavis_list.html" %}

{% block subagreement_item %}
    href="{% url 'sub_agreements:commissariat_subagreement_detail' sub_agreement.id %}">
        {{ sub_agreement }}
{% endblock %}

sub_agreements/templates/sub_agreements/preaviscompagnie_ack_form.html
{% extends "sub_agreements/preavis_form.html" %}

sub_agreements/templates/sub_agreements/preaviscompagnie_detail.html
{% extends "sub_agreements/preavis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'sub_agreements:company_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            Rendre le pré-avis
        </a>
    {% elif object.state == 'acknowledged' and object.avis.state == 'acknowledged' and not object.concerned_cis.exists %}
        <a href="{% url 'sub_agreements:notify_cis' pk=object.id %}" class="btn" role="button">
            Informer les CIS concernés
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/preaviscompagnie_notify_form.html
{% extends "sub_agreements/preavis_form.html" %}

{% load i18n %}

{% block head_title %}Choisissez les CIS concernés{% endblock %}
{% block page_title %}
    <h1>Choisissez les CIS concernés</h1>
{% endblock %}

sub_agreements/templates/sub_agreements/preavisedsr_detail.html
{% extends "sub_agreements/preavis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'sub_agreements:edsr_subagreement_acknowledge' pk=object.id %}" class="btn" role="button">
            Rendre le pré-avis
        </a>
    {% endif %}
{% endblock %}

sub_agreements/templates/sub_agreements/preavisedsr_list.html
{% extends "sub_agreements/preavis_list.html" %}

{% block subagreement_item %}
    href="{% url 'sub_agreements:edsr_subagreement_detail' sub_agreement.id %}">
        {{ sub_agreement }}
{% endblock %}

sub_agreements/templates/sub_agreements/preavisedsr_notify_form.html
{% extends "sub_agreements/preavis_form.html" %}

{% load i18n %}

{% block head_title %}Choisissez les agents concernés{% endblock %}
{% block page_title %}
    <h1>Choisissez les agents concernés</h1>
{% endblock %}

sub_agreements/templates/sub_agreements/preavisservicecg_ack_form.html
{% extends "sub_agreements/preavis_form.html" %}