agreements/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^dashboard/$', Dashboard.as_view(), name='dashboard'),

    # Service Agreements
    url(r'^service/(?P<pk>\d+)/$', ServiceAgreementDetail.as_view(), name='service_agreement_detail'),
    url(r'^service/(?P<pk>\d+)/acknowledge/$', ServiceAgreementAcknowledge.as_view(), name='service_agreement_acknowledge'),
    url(r'^service/(?P<pk>\d+)/resend/$', ServiceAgreementResend.as_view(), name='service_agreement_resend'),
    # Federal Agreements
    url(r'^federation/(?P<pk>\d+)/$', FederalAgreementDetail.as_view(), name='federal_agreement_detail'),
    url(r'^federation/(?P<pk>\d+)/acknowledge/$', FederalAgreementAcknowledge.as_view(), name='federal_agreement_acknowledge'),
    url(r'^federation/(?P<pk>\d+)/resend/$', FederalAgreementResend.as_view(), name='federal_agreement_resend'),
    # TownHall Agreements
    url(r'^townhall/(?P<pk>\d+)/$', TownHallAgreementDetail.as_view(), name='townhall_agreement_detail'),
    url(r'^townhall/(?P<pk>\d+)/acknowledge/$', TownHallAgreementAcknowledge.as_view(), name='townhall_agreement_acknowledge'),
    url(r'^townhall/(?P<pk>\d+)/resend/$', TownHallAgreementResend.as_view(), name='townhall_agreement_resend'),
    # EDSR Agreements
    url(r'^edsr/(?P<pk>\d+)/dispatch/$', EDSRAgreementDispatch.as_view(), name='edsr_agreement_dispatch'),
    url(r'^edsr/(?P<pk>\d+)/$', EDSRAgreementDetail.as_view(), name='edsr_agreement_detail'),
    url(r'^edsr/(?P<pk>\d+)/format/$', EDSRAgreementFormat.as_view(), name='edsr_agreement_format'),
    url(r'^edsr/(?P<pk>\d+)/acknowledge/$', EDSRAgreementAcknowledge.as_view(), name='edsr_agreement_acknowledge'),
    url(r'^edsr/(?P<pk>\d+)/resend/$', EDSRAgreementResend.as_view(), name='edsr_agreement_resend'),
    # GGD Agreements
    url(r'^ggd/(?P<pk>\d+)/dispatch/$', GGDAgreementDispatch.as_view(), name='ggd_agreement_dispatch'),
    url(r'^ggd/(?P<pk>\d+)/$', GGDAgreementDetail.as_view(), name='ggd_agreement_detail'),
    url(r'^ggd/(?P<pk>\d+)/format/$', GGDAgreementFormat.as_view(), name='ggd_agreement_format'),
    url(r'^ggd/(?P<pk>\d+)/acknowledge/$', GGDAgreementAcknowledge.as_view(), name='ggd_agreement_acknowledge'),
    url(r'^ggd/(?P<pk>\d+)/resend/$', GGDAgreementResend.as_view(), name='ggd_agreement_resend'),
    # SDIS Agreements
    url(r'^sdis/(?P<pk>\d+)/dispatch/$', SDISAgreementDispatch.as_view(), name='sdis_agreement_dispatch'),
    url(r'^sdis/(?P<pk>\d+)/$', SDISAgreementDetail.as_view(), name='sdis_agreement_detail'),
    url(r'^sdis/(?P<pk>\d+)/acknowledge/$', SDISAgreementAcknowledge.as_view(), name='sdis_agreement_acknowledge'),
    url(r'^sdis/(?P<pk>\d+)/resend/$', SDISAgreementResend.as_view(), name='sdis_agreement_resend'),
    # DDSP Agreements
    url(r'^ddsp/(?P<pk>\d+)/dispatch/$', DDSPAgreementDispatch.as_view(), name='ddsp_agreement_dispatch'),
    url(r'^ddsp/(?P<pk>\d+)/$', DDSPAgreementDetail.as_view(), name='ddsp_agreement_detail'),
    url(r'^ddsp/(?P<pk>\d+)/acknowledge/$', DDSPAgreementAcknowledge.as_view(), name='ddsp_agreement_acknowledge'),
    url(r'^ddsp/(?P<pk>\d+)/resend/$', DDSPAgreementResend.as_view(), name='ddsp_agreement_resend'),
    # CG Agreements
    url(r'^cg/(?P<pk>\d+)/dispatch/$', CGAgreementDispatch.as_view(), name='cg_agreement_dispatch'),
    url(r'^cg/(?P<pk>\d+)/$', CGAgreementDetail.as_view(), name='cg_agreement_detail'),
    url(r'^cg/(?P<pk>\d+)/format/$', CGAgreementFormat.as_view(), name='cg_agreement_format'),
    url(r'^cg/(?P<pk>\d+)/acknowledge/$', CGAgreementAcknowledge.as_view(), name='cg_agreement_acknowledge'),
    url(r'^cg/(?P<pk>\d+)/resend/$', CGAgreementResend.as_view(), name='cg_agreement_resend'),
]

ddcs_loire/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from events.views import ProfileDetailView
from events.views import UserUpdateView
from events.views import StructureUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'ddcs_loire.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sitemap\.xml$', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileDetailView.as_view(), name='profile'),
    url(r'^accounts/profile/edit$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    url(r'^agreements/', include('agreements.urls', namespace='agreements')),
    url(r'^sub_agreements/', include('sub_agreements.urls', namespace='sub_agreements')),
    url(r'^authorizations/', include('authorizations.urls', namespace='authorizations')),
    url(r'^declarations/', include('declarations.urls', namespace='declarations')),
    url(r'^evaluations/', include('evaluations.urls', namespace='evaluations')),
    url(r'^nouveautes/', include('nouveautes.urls', namespace='nouveautes')),
    url(r'^', include('events.urls', namespace='events')),
    url(r'^protected_areas/', include('protected_areas.urls', namespace='protected_areas')),
    url(r'^(?P<url>.*/)$', flatpages_views.flatpage),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
# coding: utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import HomePage
from .views import Dashboard
from .views import Calendar
from .views import FilteredCalendar
from .views import StructureCreate
from .views import CreateRoute
from .views import ManifestationChoose
from .views import MotorizedEventChoose
from .views import NonMotorizedEventChoose
from .views import DeclarationNMChoose
from .views import PublicRoadMotorizedEventChoose
from .views import ManifestationPublicDetail

from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate

from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate

from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate

from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate

from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate

from .views import DocumentComplementaireRequestView
from .views import DocumentComplementaireProvideView

from .views import MailToOrganisateursView
from .views import MailToTownHallsView

from sports.views import activites_par_discipline

urlpatterns = [

    url(r'^$', HomePage.as_view(),
        name='home_page'),
    url(r'^mail_to_promoters/$', MailToOrganisateursView.as_view(),
        name='mail_to_promoters'),
    url(r'^mail_to_townhalls/$', MailToTownHallsView.as_view(),
        name='mail_to_townhalls'),
    url(r'^dashboard/$', Dashboard.as_view(),
        name="dashboard"),
    url(r'^calendar/$', Calendar.as_view(),
        name="calendar"),
    url(r'^calendar/(?P<activite>\d+)/$', FilteredCalendar.as_view(),
        name="filtered_calendar"),
    url(r'^structure/add', StructureCreate.as_view(), name='structure_add'),

    url(r'^events/create_route/$', CreateRoute.as_view(),
        name='create_route'),
    url(r'^events/choose/$', ManifestationChoose.as_view(),
        name='manifestation_choose'),
    url(r'^motorizedevents/choose', MotorizedEventChoose.as_view(),
        name="motorizedevent_choose"),
    url(r'^nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(),
        name="nonmotorizedevent_choose"),
    url(r'^DeclarationNM/choose',
        DeclarationNMChoose.as_view(),
        name="declarationnm_choose"),
    url(r'^publicroadmotorizedevents/choose',
        PublicRoadMotorizedEventChoose.as_view(),
        name="publicroadmotorizedevent_choose"),
    url(r'^events/(?P<pk>\d+)/$',
        ManifestationPublicDetail.as_view(),
        name="manifestation_detail"),

    # DeclarationNM urls
    url(r'^DeclarationNM/add/$',
        DeclarationNMCreate.as_view(),
        name="declarationnm_add"),
    url(r'^DeclarationNM/(?P<pk>\d+)/$',
        DeclarationNMDetail.as_view(),
        name="declarationnm_detail"),
    url(r'^DeclarationNM/(?P<pk>\d+)/edit/$',
        DeclarationNMUpdate.as_view(),
        name="declarationnm_update"),

    # AutorisationNM urls
    url(r'^AutorisationNM/add/$',
        AutorisationNMCreate.as_view(),
        name="autorisationnm_add"),
    url(r'^AutorisationNM/(?P<pk>\d+)/$',
        AutorisationNMDetail.as_view(),
        name="autorisationnm_detail"),
    url(r'^AutorisationNM/(?P<pk>\d+)/edit/$',
        AutorisationNMUpdate.as_view(),
        name="autorisationnm_update"),

    # MotorizedConcentration urls
    url(r'^motorizedconcentrations/add/$',
        MotorizedConcentrationCreate.as_view(),
        name="motorizedconcentration_add"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/$',
        MotorizedConcentrationDetail.as_view(),
        name="motorizedconcentration_detail"),
    url(r'^motorizedconcentrations/(?P<pk>\d+)/edit/$',
        MotorizedConcentrationUpdate.as_view(),
        name="motorizedconcentration_update"),

    # MotorizedEvent urls
    url(r'^motorizedevents/add/$',
        MotorizedEventCreate.as_view(),
        name="motorizedevent_add"),
    url(r'^motorizedevents/(?P<pk>\d+)/$',
        MotorizedEventDetail.as_view(),
        name="motorizedevent_detail"),
    url(r'^motorizedevents/(?P<pk>\d+)/edit/$',
        MotorizedEventUpdate.as_view(),
        name="motorizedevent_update"),

    # MotorizedRace urls
    url(r'^motorizedraces/add/$',
        MotorizedRaceCreate.as_view(),
        name="motorizedrace_add"),
    url(r'^motorizedraces/(?P<pk>\d+)/$',
        MotorizedRaceDetail.as_view(),
        name="motorizedrace_detail"),
    url(r'^motorizedraces/(?P<pk>\d+)/edit/$',
        MotorizedRaceUpdate.as_view(),
        name="motorizedrace_update"),
    url(r'^events/(?P<manifestation_pk>\d+)/additional_data/add$',
        DocumentComplementaireRequestView.as_view(),
        name="additional_data_add"),
    url(r'^additional_data/(?P<pk>\d+)/$',
        DocumentComplementaireProvideView.as_view(),
        name="additional_data_provide"),

    url(r'^activites_par_discipline/$',
        activites_par_discipline)
]

agreements/models/abstract.py
# coding: utf-8
from django.db import models

from django_fsm import FSMField


class AvisBase(models.Model):
    """ Mixin pour les avis et préavis (+5 champs) """

    state = FSMField(default='created')  # Tout (pré)avis est à l'état 'created" par défaut
    request_date = models.DateField("Date de demande", auto_now_add=True)
    reply_date = models.DateField("Date de retour", blank=True, null=True)
    favorable = models.BooleanField("Avis favorable ?", default=False, help_text="Si coché, l'avis rendu est considéré favorable")
    prescriptions = models.TextField("prescriptions", blank=True)

    class Meta:
        abstract = True

agreements/models/mairie.py
# coding: utf-8
import datetime

from django.core.urlresolvers import reverse
from django.db import models
from django_fsm import transition

from agreements.models.avis import Avis, AvisQuerySet
from core.util.application import FILTER_ARRONDISSEMENT_CHOICES


class MairieAvis(Avis):
    """ Avis mairie """
    avis_ptr = models.OneToOneField("agreements.avis", parent_link=True,
                                    related_name='mairieavis')
    commune = models.ForeignKey('administrative_division.commune', verbose_name='commune',
                                limit_choices_to=FILTER_ARRONDISSEMENT_CHOICES)
    objects = AvisQuerySet.as_manager()

    def __str__(self):
        return ' - '.join([str(self.get_manifestation()), str(self.commune)])

    def get_absolute_url(self):
        """ Renvoyer l'URL de l'avis """
        return reverse('agreements:townhall_agreement_detail', kwargs={'pk': self.pk})

    def get_agents(self):
        """ Renvoyer les agents concernés par l'avis """
        return self.commune.get_mairieagents()

    @transition(field='state', source='created', target='acknowledged')
    def acknowledge(self):
        """ Rendre l'avis """
        self.reply_date = datetime.date.today()
        self.save()
        self.notify_ack(content_object=self.commune)
        self.log_ack(agents=self.get_agents())

    class Meta:
        verbose_name = 'avis mairie'
        verbose_name_plural = 'avis mairies'
        app_label = 'agreements'
        default_related_name = 'mairieaviss'

agreements/forms/acknowledge.py
# coding: utf-8
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, Layout

from agreements.models import Avis
from ddcs_loire.utils import GenericForm


class AvisAcknowledgeForm(GenericForm):
    """ Formulaire de rendu d'avis (acknowledge) """

    def __init__(self, *args, **kwargs):
        super(AvisAcknowledgeForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                'favorable',
                'prescriptions',
                'attached_document',
                FormActions(Submit('save', "rendre l'avis".capitalize()))
        )

    class Meta:
        model = Avis
        fields = ['favorable', 'prescriptions', 'attached_document']

agreements/forms/dispatch.py
# coding: utf-8
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, Layout

from agreements.models import CGAvis
from agreements.models import DDSPAvis
from agreements.models import EDSRAvis
from agreements.models import GGDAvis
from agreements.models import SDISAvis
from ddcs_loire.utils import GenericForm


class DDSPAvisDispatchForm(GenericForm):
    """ Formulaire de dispatchage d'avis """

    def __init__(self, *args, **kwargs):
        super(DDSPAvisDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                'commissariats_concernes',
                FormActions(
                        Submit('save', "envoyer les demandes de pré-avis".capitalize())
                )
        )

    class Meta:
        model = DDSPAvis
        fields = ('commissariats_concernes',)


class EDSRAvisDispatchForm(GenericForm):
    """ Formulaire de dispatchage d'avis """

    def __init__(self, *args, **kwargs):
        super(EDSRAvisDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                'concerned_cgd',
                FormActions(
                        Submit('save', "envoyer les demandes de pré-avis".capitalize())
                )
        )

    class Meta:
        model = EDSRAvis
        fields = ('concerned_cgd',)


class GGDAvisDispatchForm(GenericForm):
    """ Formulaire de dispatchage d'avis """

    def __init__(self, *args, **kwargs):
        super(GGDAvisDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                'concerned_cgd',
                'concerned_edsr',
                FormActions(
                        Submit('save', "Envoyer la demande de préavis".capitalize())
                )
        )

    class Meta:
        model = GGDAvis
        fields = ('concerned_cgd', 'concerned_edsr')


class SDISAvisDispatchForm(GenericForm):
    """ Formulaire de dispatchage d'avis """

    def __init__(self, *args, **kwargs):
        super(SDISAvisDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                'compagnies_concernees',
                FormActions(
                        Submit('save', "envoyer les demandes de pré-avis".capitalize())
                )
        )

    class Meta:
        model = SDISAvis
        fields = ("compagnies_concernees",)


class CGAvisDispatchForm(GenericForm):
    """ Formulaire de dispatchage d'avis """

    def __init__(self, *args, **kwargs):
        super(CGAvisDispatchForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                'concerned_services',
                FormActions(
                        Submit('save', "envoyer les demandes de pré-avis".capitalize())
                )
        )

    class Meta:
        model = CGAvis
        fields = ['concerned_services']

agreements/forms/format.py
# coding: utf-8
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, Layout

from agreements.models import Avis
from ddcs_loire.utils import GenericForm


class AvisFormatForm(GenericForm):
    """ Formulaire de mise en forme d'avis """

    def __init__(self, *args, **kwargs):
        super(AvisFormatForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
                'favorable',
                'prescriptions',
                'attached_document',
                FormActions(
                        Submit('save', "mettre en forme l'avis".capitalize())
                )
        )

    class Meta:
        model = Avis
        fields = ('favorable', 'prescriptions', 'attached_document')

agreements/templates/agreements/avis_format_form.html
{% extends "events/base_form.html" %}

{% load i18n %}

{% block head_title %}
    Mettre en forme l'avis
{% endblock %}

{% block page_title %}
    <h1>Mettre en forme l'avis</h1>
{% endblock %}

agreements/templates/agreements/avis_list.html
{% extends "events/base.html" %}

{# load url from future #}
{% load i18n %}

{% block head_title %}
    Tableau de bord
{% endblock %}

{% block page_title %}
    <h1><i class="fa fa-tachometer" aria-hidden="true"></i> Tableau de bord</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3>
                <i class="fa fa-bookmark" aria-hidden="true"></i> Avis demandés
            </h3>

            <div class="panel panel-default">
                <div class="list-group">
                    {% for avis in object_list %}
                        <a class="list-group-item
                            {% if avis.state == 'acknowledged' %}
                                list-group-item-success
                            {% elif avis.state == 'dispatched' %}
                                list-group-item-warning
                            {% elif avis.state == 'formatted' %}
                                list-group-item-warning
                            {% elif avis.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                        {% block agreement_item %}{% endblock %}
                        {% if avis.get_days_left_before_deadline.days > 0 and not avis.state == 'acknowledged' %}
                            <span class="label label-default pull-right">Délai : {{ avis.get_days_left_before_deadline.days }} jours</span>
                        {% endif %}
                        {% if avis.sub_agreements_missing %}
                            <span class="label label-default pull-right">{{ avis.sub_agreements_missing }} préavis manquants</span>
                        {% endif %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucun avis à gérer</a>
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
        {% include "notifications/actions_list.html" %}
    </div>
    <div class="col-sm-6">
        {% include "notifications/notifications_list.html" %}
    </div>
    </div>
{% endblock %}

agreements/templates/agreements/cgavis_detail.html
{% extends "agreements/avis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' and request.user.agent.cgagent %}
        <a href="{% url 'agreements:cg_agreement_dispatch' pk=object.id %}" class="btn" role="button">
            <i class="fa fa-tags" aria-hidden="true"></i>Envoyer les demandes de pré-avis
        </a>
    {% elif object.state == 'dispatched' and request.user.agent.cgagent %}
        {% if object.preavis_validated %}
            <a href="{% url 'agreements:cg_agreement_format' pk=object.id %}" class="btn" role="button">
                <i class="fa fa-pencil" aria-hidden="true"></i>Mettre en forme l'avis
            </a>
        {% endif %}
    {% elif object.state == 'formatted' and request.user.agent.cgsuperieuragent%}
        <a href="{% url 'agreements:cg_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
            <i class="fa fa-bookmark" aria-hidden="true"></i>Rendre l'avis
        </a>
    {% endif %}
{% endblock %}

agreements/templates/agreements/cgavis_dispatch_form.html
{% extends "agreements/avis_dispatch_form.html" %}

agreements/templates/agreements/cgavis_list.html
{% extends "agreements/avis_list.html" %}

{% block agreement_item %}
    href="{% url 'agreements:cg_agreement_detail' avis.id %}">
        {{ avis.authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ avis.authorization.manifestation }}
{% endblock %}

agreements/templates/agreements/ddspavis_list.html
{% extends "agreements/avis_list.html" %}

{% block agreement_item %}
    href="{% url 'agreements:ddsp_agreement_detail' avis.id %}">
        {{ avis.authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ avis.authorization.manifestation }}
{% endblock %}

agreements/templates/agreements/edsravis_list.html
{% extends "agreements/avis_list.html" %}

{% block agreement_item %}
    href="{% url 'agreements:edsr_agreement_detail' avis.id %}">
        {{ avis.authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ avis.authorization.manifestation }}
{% endblock %}

agreements/templates/agreements/federationavis_detail.html
{% extends "agreements/avis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' and not object.delay_exceeded %}
        <a href="{% url 'agreements:federal_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
            Rendre l'avis
        </a>
    {% endif %}
{% endblock %}

agreements/templates/agreements/ggdavis_list.html
{% extends "agreements/avis_list.html" %}

{% block agreement_item %}
    href="{% url 'agreements:ggd_agreement_detail' avis.id %}">
        {{ avis.authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ avis.authorization.manifestation }}
{% endblock %}

agreements/templates/agreements/mairieavis_list.html
{% extends "agreements/avis_list.html" %}

{% block agreement_item %}
    href="{% url 'agreements:townhall_agreement_detail' avis.id %}">
        {{ avis.authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ avis.authorization.manifestation }}
{% endblock %}

agreements/templates/agreements/sdisavis_ack_form.html
{% extends "agreements/avis_ack_form.html" %}

agreements/templates/agreements/sdisavis_detail.html
{% extends "agreements/avis_detail.html" %}

{% load i18n %}

{% block agreement_actions %}
    {% if object.state == 'created' %}
        <a href="{% url 'agreements:sdis_agreement_dispatch' pk=object.id %}" class="btn" role="button">
            <i class="fa fa-tags" aria-hidden="true"></i>Envoyer les demandes de pré-avis
        </a>
    {% elif object.state == 'dispatched' %}
        {% if object.preavis_validated %}
            <a href="{% url 'agreements:sdis_agreement_acknowledge' pk=object.id %}" class="btn" role="button">
                Rendre l'avis
            </a>
        {% endif %}
    {% endif %}
{% endblock %}

agreements/templates/agreements/sdisavis_list.html
{% extends "agreements/avis_list.html" %}

{% block agreement_item %}
    href="{% url 'agreements:sdis_agreement_detail' avis.id %}">
        {{ avis.authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ avis.authorization.manifestation }}
{% endblock %}

agreements/templates/agreements/serviceavis_ack_form.html
{% extends "events/base_form.html" %}

{% load i18n %}

{% block head_title %}Rendre l'avis{% endblock %}
{% block page_title %}
    <h1>Rendre l'avis</h1>
{% endblock %}